# Config for https://github.com/toolmantim/release-drafter
name-template: 'sbt-paradox-dependencies $NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
      labels:
        - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'

change-template: '- $TITLE [#$NUMBER](https://github.com/lightbend/sbt-paradox-dependencies/issues/$NUMBER) by [@$AUTHOR](https://github.com/$AUTHOR)'
template: |
  ## Changes

  $CHANGES
