language: scala
jdk: oraclejdk8
scala: 2.12.10

jobs:
  include:
    - stage: test
      script: sbt scalafmtCheck scalafmtSbtCheck
      name: "Formatting check"
    - script: sbt ";^test ;^scripted"
      name: "Tests run"
    - stage: publish
      script: sbt ";^publish"
      name: "Publish"

stages:
  - name: test # runs on master commits and PRs
    if: NOT tag =~ ^v
  - name: publish # runs on main repo master commits or version-tagged commits
    if: repo = lightbend/sbt-paradox-dependencies AND ( ( branch = master AND type = push ) OR tag =~ ^v )

cache:
  directories:
    - $HOME/.sbt
    - $HOME/cache/coursier/v1

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

notifications:
  email:
    on_success: never

env:
  global:
    # travis encrypt BINTRAY_USER=...
    - secure: "ZhnhCYL6LAWrAWljMB690IjBsATtxA0GkvtzAejYd/RLtMcc0pndLkqBWQCkflibpypi4h5VyIvtZ5c1h8I0x5N2Und0zROchCyumfa5C0vEnILetJIcWFA+fisqaLxljQpLE5wCa59laQpzwSOUwtdF9Sa7pWjo2fnhInabbBwzCEVjLlqdAb6cZz5pUdkoo3vQxoO4xqFuAfLBLrEiQQgyFnK4/FLcNf+0rFIoNuz9Al0mmc0tRLk+oVHx+MmixZR8xqmzO8UAMTmmOX7ImYrywdwlCagY0RgeonjVIURBzad7D+GiUCaXG1pJ5j7l1Uw4FY3Vye/Qm/OihAmNs0lXqVCoBn6nWztgG33LqPwqQXA8bb5U7qQFFoKooUlASPyic0yxSzmsV3AudZAPmXvmAsyfXADWIUaQlFVCBoe+J4pQ+htn7+pGwydn0Aw9qdpvWUBZM81GFRxcJRl/Zbgt6/oOUBVyjiPsycPtLlcQJC0NWiEldZA1YYXmQA88013P58IqSeUbnyfMboPk0oaYRgq22Ebr28nShrvT+fgO4ypJ62qvqgsueC1jaF3btFKKodhW+eRhXR9OEN1EZLvLbJ4FNS7daPFxI+oanh4JfNfYsZBYOoFQuiZHCOQ+UE3oD3O1Id91QeCCAzwLtKjfDif8z211yQ2vfnVhlpY="
    # travis encrypt BINTRAY_PASS=...
    - secure: "ieV7nuLdoMYV76tHy6ymTg8wrvIxrVSBwayLR2tdJ4nqcaoalU37mDpJSs2IQSXW84OU5eGSqUz0oJpHk1SaoZEIcVXgw8zCaPgr0QMB8joHttNUc3jOoxmFwrLmp5lrjBn8LQ52IhMVcgjED3yBpNwzoPPq00sklILkrkbpdqgiwgTnqmt7AOBdCnhnsEeUO4fQ07PqdXvQwE+SQIAF1hh6cQ1BiOWaR2mCjkrI1icXZqCylIloMS6dzv8EZOnFJxFCK2KccDr+607IleWxGKYrNgb8G4ihObc6XvuLiJFGoYxxtx6weYSOWcz1BjYBrHo6AyFkB56uGPwdz+VB5ybWfiKEDXsCqFolHZBfQkrtkUsQ25Vs3etSHgvEcaPnSYROX+wuQKnGUzQNvU4n6C04iuF/DepF8oqR+Txqvkc9i2oolkAkRrOboRmBVJt9adeiB/NWz1WmIwpcKBQAHRG5/PHv8xxaVXYK8ElGI0KOkfhR8RpOIVQ32asGFpDTwlMF/ZccqoybuyG5yrARLseV4NxXQb52TvOApxezvknZmunnwtcQLdzca932Vhq6sdMYBmtOJTNyZDuRjYN1ydcjiKq0caVZFI/4ZZOlgxnDJD+sRzyRrLGWBMvTG3vljTDwCCmI3toQJngK+3XM4JiLbLu2AvpbvEc7ZYSkyiE="
